# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow, QWidget {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 1px solid #333333;\n"
"    border-radius: 4px;\n"
"    padding: 4px 8px;\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"\n"
"QLineEdit, QComboBox, QSpinBox {\n"
"    border: 1px solid #333333;\n"
"    border-radius: 3px;\n"
"    padding: 2px 4px;\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #333333;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #d8d8d8;\n"
"    color: #000000;\n"
"    border: 1px solid #333333;\n"
"    border-bottom: none;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #ffffff;\n"
"    color: #000000;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background-color: #e8e8e8;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #333333;\n"
"    border-radius: 4px;\n"
"    margin-top: 8px;\n"
"    padding-top: 8px;\n"
"    color: #000000;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 8px;\n"
"    padding: 0 4px;\n"
"    color: #000000;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_archivo = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_archivo.setObjectName("verticalLayout_archivo")
        self.label_archivoTitulo = QtWidgets.QLabel(parent=self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_archivoTitulo.setFont(font)
        self.label_archivoTitulo.setObjectName("label_archivoTitulo")
        self.verticalLayout_archivo.addWidget(self.label_archivoTitulo)
        self.pushButton_nuevoPedido = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_nuevoPedido.setObjectName("pushButton_nuevoPedido")
        self.verticalLayout_archivo.addWidget(self.pushButton_nuevoPedido)
        self.pushButton_abrirCaja = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_abrirCaja.setObjectName("pushButton_abrirCaja")
        self.verticalLayout_archivo.addWidget(self.pushButton_abrirCaja)
        self.pushButton_cerrarTurno = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_cerrarTurno.setObjectName("pushButton_cerrarTurno")
        self.verticalLayout_archivo.addWidget(self.pushButton_cerrarTurno)
        self.pushButton_exportarReporte = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_exportarReporte.setObjectName("pushButton_exportarReporte")
        self.verticalLayout_archivo.addWidget(self.pushButton_exportarReporte)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_archivo.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_edicion = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_edicion.setObjectName("verticalLayout_edicion")
        self.label_edicionTitulo = QtWidgets.QLabel(parent=self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_edicionTitulo.setFont(font)
        self.label_edicionTitulo.setObjectName("label_edicionTitulo")
        self.verticalLayout_edicion.addWidget(self.label_edicionTitulo)
        self.pushButton_editarMenu = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_editarMenu.setObjectName("pushButton_editarMenu")
        self.verticalLayout_edicion.addWidget(self.pushButton_editarMenu)
        self.pushButton_editarPrecios = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_editarPrecios.setObjectName("pushButton_editarPrecios")
        self.verticalLayout_edicion.addWidget(self.pushButton_editarPrecios)
        self.pushButton_editarPromociones = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_editarPromociones.setObjectName("pushButton_editarPromociones")
        self.verticalLayout_edicion.addWidget(self.pushButton_editarPromociones)
        self.pushButton_editarCategorias = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_editarCategorias.setObjectName("pushButton_editarCategorias")
        self.verticalLayout_edicion.addWidget(self.pushButton_editarCategorias)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_edicion.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_ver = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_ver.setObjectName("verticalLayout_ver")
        self.label_verTitulo = QtWidgets.QLabel(parent=self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_verTitulo.setFont(font)
        self.label_verTitulo.setObjectName("label_verTitulo")
        self.verticalLayout_ver.addWidget(self.label_verTitulo)
        self.pushButton_verVentas = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButton_verVentas.setObjectName("pushButton_verVentas")
        self.verticalLayout_ver.addWidget(self.pushButton_verVentas)
        self.pushButton_verInventario = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButton_verInventario.setObjectName("pushButton_verInventario")
        self.verticalLayout_ver.addWidget(self.pushButton_verInventario)
        self.pushButton_verHistorial = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButton_verHistorial.setObjectName("pushButton_verHistorial")
        self.verticalLayout_ver.addWidget(self.pushButton_verHistorial)
        self.pushButton_verClientes = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButton_verClientes.setObjectName("pushButton_verClientes")
        self.verticalLayout_ver.addWidget(self.pushButton_verClientes)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_ver.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_settingsRoot = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_settingsRoot.setObjectName("verticalLayout_settingsRoot")
        self.scrollArea_settings = QtWidgets.QScrollArea(parent=self.tab_4)
        self.scrollArea_settings.setWidgetResizable(True)
        self.scrollArea_settings.setObjectName("scrollArea_settings")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 760, 514))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_settings = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_settings.setObjectName("verticalLayout_settings")
        self.label_settingsTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_settingsTitle.setFont(font)
        self.label_settingsTitle.setObjectName("label_settingsTitle")
        self.verticalLayout_settings.addWidget(self.label_settingsTitle)
        self.formLayout_settings = QtWidgets.QFormLayout()
        self.formLayout_settings.setObjectName("formLayout_settings")
        self.label_nombreUsuario = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_nombreUsuario.setObjectName("label_nombreUsuario")
        self.formLayout_settings.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_nombreUsuario)
        self.nombre_usuario = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.nombre_usuario.setObjectName("nombre_usuario")
        self.formLayout_settings.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nombre_usuario)
        self.label_temaInterfaz = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_temaInterfaz.setObjectName("label_temaInterfaz")
        self.formLayout_settings.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_temaInterfaz)
        self.tema_interfaz = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.tema_interfaz.setObjectName("tema_interfaz")
        self.tema_interfaz.addItem("")
        self.tema_interfaz.addItem("")
        self.formLayout_settings.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tema_interfaz)
        self.label_idioma = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_idioma.setObjectName("label_idioma")
        self.formLayout_settings.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_idioma)
        self.idioma = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.idioma.setObjectName("idioma")
        self.idioma.addItem("")
        self.idioma.addItem("")
        self.formLayout_settings.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.idioma)
        self.label_tamanoFuente = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_tamanoFuente.setObjectName("label_tamanoFuente")
        self.formLayout_settings.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_tamanoFuente)
        self.tamano_fuente = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.tamano_fuente.setMinimum(1)
        self.tamano_fuente.setMaximum(72)
        self.tamano_fuente.setObjectName("tamano_fuente")
        self.formLayout_settings.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tamano_fuente)
        self.label_colorMenu = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_colorMenu.setObjectName("label_colorMenu")
        self.formLayout_settings.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_colorMenu)
        self.horizontalLayout_colorMenu = QtWidgets.QHBoxLayout()
        self.horizontalLayout_colorMenu.setObjectName("horizontalLayout_colorMenu")
        self.color_menu_swatch = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.color_menu_swatch.setMinimumSize(QtCore.QSize(28, 22))
        self.color_menu_swatch.setMaximumSize(QtCore.QSize(28, 22))
        self.color_menu_swatch.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.color_menu_swatch.setStyleSheet("background-color: #d8d8d8;")
        self.color_menu_swatch.setObjectName("color_menu_swatch")
        self.horizontalLayout_colorMenu.addWidget(self.color_menu_swatch)
        self.pushButton_colorMenu = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton_colorMenu.setObjectName("pushButton_colorMenu")
        self.horizontalLayout_colorMenu.addWidget(self.pushButton_colorMenu)
        self.formLayout_settings.setLayout(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_colorMenu)
        self.label_colorLetra = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_colorLetra.setObjectName("label_colorLetra")
        self.formLayout_settings.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_colorLetra)
        self.horizontalLayout_colorLetra = QtWidgets.QHBoxLayout()
        self.horizontalLayout_colorLetra.setObjectName("horizontalLayout_colorLetra")
        self.color_letra_swatch = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.color_letra_swatch.setMinimumSize(QtCore.QSize(28, 22))
        self.color_letra_swatch.setMaximumSize(QtCore.QSize(28, 22))
        self.color_letra_swatch.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.color_letra_swatch.setStyleSheet("background-color: #000000;")
        self.color_letra_swatch.setObjectName("color_letra_swatch")
        self.horizontalLayout_colorLetra.addWidget(self.color_letra_swatch)
        self.pushButton_colorLetra = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton_colorLetra.setObjectName("pushButton_colorLetra")
        self.horizontalLayout_colorLetra.addWidget(self.pushButton_colorLetra)
        self.formLayout_settings.setLayout(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_colorLetra)
        self.verticalLayout_settings.addLayout(self.formLayout_settings)
        self.line_1 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_1.setObjectName("line_1")
        self.verticalLayout_settings.addWidget(self.line_1)
        self.groupBox_fotoPerfil = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.groupBox_fotoPerfil.setObjectName("groupBox_fotoPerfil")
        self.horizontalLayout_fotoPerfil = QtWidgets.QHBoxLayout(self.groupBox_fotoPerfil)
        self.horizontalLayout_fotoPerfil.setObjectName("horizontalLayout_fotoPerfil")
        self.foto_perfil = QtWidgets.QLabel(parent=self.groupBox_fotoPerfil)
        self.foto_perfil.setMinimumSize(QtCore.QSize(120, 120))
        self.foto_perfil.setMaximumSize(QtCore.QSize(120, 120))
        self.foto_perfil.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.foto_perfil.setScaledContents(True)
        self.foto_perfil.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.foto_perfil.setObjectName("foto_perfil")
        self.horizontalLayout_fotoPerfil.addWidget(self.foto_perfil)
        self.verticalLayout_fotoBotones = QtWidgets.QVBoxLayout()
        self.verticalLayout_fotoBotones.setObjectName("verticalLayout_fotoBotones")
        self.pushButton_seleccionarFoto = QtWidgets.QPushButton(parent=self.groupBox_fotoPerfil)
        self.pushButton_seleccionarFoto.setObjectName("pushButton_seleccionarFoto")
        self.verticalLayout_fotoBotones.addWidget(self.pushButton_seleccionarFoto)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_fotoBotones.addItem(spacerItem3)
        self.horizontalLayout_fotoPerfil.addLayout(self.verticalLayout_fotoBotones)
        self.verticalLayout_settings.addWidget(self.groupBox_fotoPerfil)
        self.line_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_settings.addWidget(self.line_2)
        self.horizontalLayout_settingsActions = QtWidgets.QHBoxLayout()
        self.horizontalLayout_settingsActions.setObjectName("horizontalLayout_settingsActions")
        self.pushButton_guardarCambios = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton_guardarCambios.setObjectName("pushButton_guardarCambios")
        self.horizontalLayout_settingsActions.addWidget(self.pushButton_guardarCambios)
        self.pushButton_restablecerValores = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton_restablecerValores.setObjectName("pushButton_restablecerValores")
        self.horizontalLayout_settingsActions.addWidget(self.pushButton_restablecerValores)
        self.verticalLayout_settings.addLayout(self.horizontalLayout_settingsActions)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_settings.addItem(spacerItem4)
        self.scrollArea_settings.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_settingsRoot.addWidget(self.scrollArea_settings)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_archivoTitulo.setText(_translate("MainWindow", "Gestión de pedidos y archivos"))
        self.pushButton_nuevoPedido.setText(_translate("MainWindow", "Nuevo pedido"))
        self.pushButton_abrirCaja.setText(_translate("MainWindow", "Abrir caja registradora"))
        self.pushButton_cerrarTurno.setText(_translate("MainWindow", "Cerrar turno"))
        self.pushButton_exportarReporte.setText(_translate("MainWindow", "Exportar reporte del día"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Archivo"))
        self.label_edicionTitulo.setText(_translate("MainWindow", "Edición del menú y productos"))
        self.pushButton_editarMenu.setText(_translate("MainWindow", "Editar menú"))
        self.pushButton_editarPrecios.setText(_translate("MainWindow", "Editar precios"))
        self.pushButton_editarPromociones.setText(_translate("MainWindow", "Editar promociones"))
        self.pushButton_editarCategorias.setText(_translate("MainWindow", "Editar categorías de productos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Edicion"))
        self.label_verTitulo.setText(_translate("MainWindow", "Vistas y reportes"))
        self.pushButton_verVentas.setText(_translate("MainWindow", "Ver ventas del día"))
        self.pushButton_verInventario.setText(_translate("MainWindow", "Ver inventario"))
        self.pushButton_verHistorial.setText(_translate("MainWindow", "Ver historial de pedidos"))
        self.pushButton_verClientes.setText(_translate("MainWindow", "Ver clientes frecuentes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Ver"))
        self.label_settingsTitle.setText(_translate("MainWindow", "Configuración"))
        self.label_nombreUsuario.setText(_translate("MainWindow", "Nombre de usuario"))
        self.label_temaInterfaz.setText(_translate("MainWindow", "Tema de interfaz"))
        self.tema_interfaz.setItemText(0, _translate("MainWindow", "Claro"))
        self.tema_interfaz.setItemText(1, _translate("MainWindow", "Oscuro"))
        self.label_idioma.setText(_translate("MainWindow", "Idioma"))
        self.idioma.setItemText(0, _translate("MainWindow", "es (es-ES)"))
        self.idioma.setItemText(1, _translate("MainWindow", "en (en-US)"))
        self.label_tamanoFuente.setText(_translate("MainWindow", "Tamaño de fuente"))
        self.label_colorMenu.setText(_translate("MainWindow", "Color de la barra de menú"))
        self.pushButton_colorMenu.setText(_translate("MainWindow", "Seleccionar color..."))
        self.label_colorLetra.setText(_translate("MainWindow", "Color de letra"))
        self.pushButton_colorLetra.setText(_translate("MainWindow", "Seleccionar color..."))
        self.groupBox_fotoPerfil.setTitle(_translate("MainWindow", "Foto de perfil"))
        self.foto_perfil.setText(_translate("MainWindow", "Sin foto"))
        self.pushButton_seleccionarFoto.setText(_translate("MainWindow", "Seleccionar imagen..."))
        self.pushButton_guardarCambios.setText(_translate("MainWindow", "Guardar cambios"))
        self.pushButton_restablecerValores.setText(_translate("MainWindow", "Restablecer valores predeterminados"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
